apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-k8-app-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
